title: ""
description: ""
theme: 

logo: /assets/profile.jpg
favicon: /assets/favicon.ico

show_title: false
show_downloads: false

github:
  is_project_page: false

social_links:
  linkedin: https://linkedin.com/in/tejas-sridhar
  github: https://github.com/tejassridharlive
  email: tejassridhar.acad@gmail.com

